{
  "hash": "d2b59e74104489f05021e4e5eb0aaa11",
  "result": {
    "markdown": "---\ntitle: \"Mini-Project 5: Discussing p-values\"\nauthor: \"Tanner Bessette\"\ndate: \"04-18-2025\"\nformat: pdf\n---\n\n\n## Statement of Integrity\n\nI have followed all rules for collaboration for this project, and I have not used generative AI on this project. Tanner Bessette\n\n## Question of interest and overview\n\nThe question of interest that I am answering for this project is: What is the probability that Nadal wins a point on his own serve, against his primary rival, Djokovic, on a clay court at the French Open?\n\nAn appropriate distribution for this data is a Binomial distribution, because Nadal either won a point or did not win a point on each of his serves. The conjugate prior (that we used in class) for Binomial data is the Beta distribution.\n\nI will be answering this question using Bayesian analyses with three priors: a non-informative prior, an informative prior based on a clay court match the two played in the previous year, and an informative prior based on a sports announcer.\n\n## Justifying decisions made to make the two informative priors\n\n**Non-informative prior:** Beta(1,1)\n\n**Informative prior based on a clay-court match the two played in the previous year. In that match, Nadal won 46 out of 66 points on his own serve. The standard error of this estimate is 0.05657:**\n\nWant $\\mu = 46/66 = 0.69697$, so $46/66 = \\alpha / (\\alpha + \\beta)$\n\n--> $46/66 * (\\alpha + \\beta) = \\alpha$\n\n--> $46/66 * \\beta = 20/66 * \\alpha$\n\nand want $\\sigma = 0.05657$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tibble)\nlibrary(tidyverse)\n\ntarget_mean <- 0.69697\n\nalphas <- seq(0.1, 100, length.out = 1000)\nbetas <- (20/66) * alphas / (46/66)\n\nparam_df <- tibble(alphas, betas)\nparam_df <- param_df |> mutate(vars = (alphas * betas) / \n                   ((alphas + betas)^2 * (alphas + betas + 1)))\n\ntarget_var <- 0.05657^2\n\nparam_df <- param_df |> mutate(dist_to_target = abs(vars - target_var))\nparam_df\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,000 x 4\n   alphas  betas   vars dist_to_target\n    <dbl>  <dbl>  <dbl>          <dbl>\n 1    0.1 0.0435 0.185          0.182 \n 2    0.2 0.0870 0.164          0.161 \n 3    0.3 0.130  0.148          0.144 \n 4    0.4 0.174  0.134          0.131 \n 5    0.5 0.217  0.123          0.120 \n 6    0.6 0.261  0.113          0.110 \n 7    0.7 0.304  0.105          0.102 \n 8    0.8 0.348  0.0983         0.0951\n 9    0.9 0.391  0.0922         0.0890\n10    1   0.435  0.0867         0.0835\n# i 990 more rows\n```\n:::\n\n```{.r .cell-code}\nparam_df |> filter(dist_to_target == min(dist_to_target))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 x 4\n  alphas betas    vars dist_to_target\n   <dbl> <dbl>   <dbl>          <dbl>\n1   45.3  19.7 0.00320   0.0000000904\n```\n:::\n:::\n\n\nSo, for the informative prior based on a clay-court match the two played in the previous year, we will use: Beta(45.3, 19.7).\n\n\n**Informative prior based on a sports announcer, who claims that they think Nadal wins about 75% of the points on his serve against Djokovic. They are also “almost sure” that Nadal wins no less than 70% of his points on serve against Djokovic:**\n\nWant $\\mu = 0.75$, so $\\alpha / (\\alpha + \\beta) = 0.75$\n\n--> $0.75 * (\\alpha + \\beta)$ = $\\alpha$\n\n--> $0.75 * \\beta$ $=$ $0.25 * \\alpha$\n\n(We will treat \"almost sure\" as a $0.02$ chance)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## trying to get a mean of 0.75 and a probability\n## that lambda is less than 0.70 equal to 0.02\nalphas <- seq(0.01, 500, length.out = 2000) \nbetas <- alphas * 0.25 / 0.75\n\ntarget_prob <- 0.02\nprob_less_point_70 <- pbeta(0.70, alphas, betas)\n\ntibble(alphas, betas, prob_less_point_70) |>\n  mutate(close_to_target = abs(prob_less_point_70 - target_prob)) |>\n  filter(close_to_target == min(close_to_target))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 x 4\n  alphas betas prob_less_point_70 close_to_target\n   <dbl> <dbl>              <dbl>           <dbl>\n1   252.  84.0             0.0200       0.0000155\n```\n:::\n:::\n\n\nSo, for the informative prior with Nadal winning 75% of the points on his serves and \"almost sure\" that Nadal wins no less than 70% of his serves we will use: Beta(252, 84).\n\n**What did I assume when I made these priors?**\n\nFor both of the informative priors, we are assuming independence of each serve, and that there is no effect of player momentum, fans, or weather on whether or not Nadal wins his serve. \n\nFor the informative prior based on the previous year's match, we are assuming that this game last year is indicative of the players' abilities in the French Open this year. \n\nFor the sports announcer informative prior, we are assuming that it is okay to use 0.98 as \"almost sure\", and we are assuming that the sports announcer is well-educated on tennis.\n\n## Graph of three priors\n\nCode for graphing priors:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nps <- seq(0, 1, length.out = 1000)\n\nnoninformative_alpha <- 1\nnoninformative_beta <- 1\n\ninformative_alpha_last_year <- 45.3 \ninformative_beta_last_year <- 19.7 \n\ninformative_alpha_announcer <- 252 \ninformative_beta_announcer <- 84  \n\nnoninformative_prior <- dbeta(ps, noninformative_alpha,\n                              noninformative_beta)\n\ninformative_prior_last_year <- dbeta(ps, informative_alpha_last_year,\n                           informative_beta_last_year)\n\ninformative_prior_announcer <- dbeta(ps, informative_alpha_announcer,\n                           informative_beta_announcer)\n\nprior_plot <- tibble(ps, noninformative_prior,\n  informative_prior_last_year, informative_prior_announcer) |>\n  pivot_longer(2:4, names_to = \"prior_type\", values_to = \"density\")\n\nggplot(data = prior_plot, aes(x = ps, y = density, \n                              colour = prior_type)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-pdf/unnamed-chunk-3-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n## Graph of three posteriors (and work to obtain them)\n\nNow, we want to use the 2020 French Open data to update our prior for the probability that Nadal wins a point on serve. In that tournament, the two players played in the final. In that final, Nadal served 84 points and won 56 of those points.\n\n**Work for non-informative posterior:**\n\nBeta(1,1) --> Beta(1 + 56, 1 + 84 - 56) --> Beta(57, 29) is the posterior distribution.\n\nPosterior mean: 57 / (57 + 29) = 57/86 = 0.6628\n\n90% credible interval for p:\n\n::: {.cell}\n\n```{.r .cell-code}\nc(qbeta(0.025, 57, 29), qbeta(0.975, 57, 29))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5601601 0.7582486\n```\n:::\n:::\n\n\nAccording to our model, there is a 90% chance that the proportion of serves that Nadal would win is between 0.5602 and 0.7582.\n\n**Work for informative posterior based on last year's match:**\n\nBeta(45.3, 19.7) --> Beta(45.3 + 56, 19.7 + 84 - 56) --> \nBeta(101.3, 47.7) is the posterior distribution.\n\nPosterior mean: 101.3 / (101.3 + 47.7) = 0.6798658\n\n90% credible interval for p:\n\n::: {.cell}\n\n```{.r .cell-code}\nc(qbeta(0.025, 101.3, 47.7), qbeta(0.975, 101.3, 47.7))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6030531 0.7521048\n```\n:::\n:::\n\n\nAccording to our model, there is a 90% chance that the proportion of serves that Nadal would win is between 0.6031 and 0.7521.\n\n**Work for informative posterior based on announcer:**\n\nBeta(252, 84) --> Beta(252 + 56, 84 + 84 - 56) --> Beta(308, 112) is the posterior distribution.\n\nPosterior mean: 308 / (308 + 112) = 0.7333\n\n90% credible interval for p:\n\n::: {.cell}\n\n```{.r .cell-code}\nc(qbeta(0.025, 308, 112), qbeta(0.975, 308, 112))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6900703 0.7744917\n```\n:::\n:::\n\n\nAccording to our model, there is a 90% chance that the proportion of serves that Nadal would win is between 0.6901 and 0.7745.\n\n**Code for graphing posteriors:**\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nps <- seq(0, 1, length.out = 1000)\n\nnoninformative_alpha <- 57\nnoninformative_beta <- 29\n\ninformative_alpha_last_year <- 101.3\ninformative_beta_last_year <- 47.7\n\ninformative_alpha_announcer <- 308\ninformative_beta_announcer <- 112\n\nnoninformative_posterior <- dbeta(ps, noninformative_alpha,\n                              noninformative_beta)\n\ninformative_posterior_last_year <- dbeta(ps, informative_alpha_last_year,\n                           informative_beta_last_year)\n\ninformative_posterior_announcer <- dbeta(ps, informative_alpha_announcer,\n                           informative_beta_announcer)\n\nprior_plot <- tibble(ps, noninformative_posterior,\n  informative_posterior_last_year, informative_posterior_announcer) |>\n  pivot_longer(2:4, names_to = \"posterior_type\", values_to = \"density\")\n\nggplot(data = prior_plot, aes(x = ps, y = density, \n                              colour = posterior_type)) +\n  geom_line() +\n  scale_colour_viridis_d(end = 0.9) +\n  theme_minimal() +\n  labs(x = \"p\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Comparison of the three posteriors\n\n**They should be a bit different from each other: why?**\n\nThey are different from each other because the prior distributions are all different. So, some posteriors are updated with greater or smaller changes based on the data that is observed. The priors all had different alpha and beta parameters, so the variances and means of the posteriors are all different.\n\n**If you had to choose one to use, which one would you choose here and why?**\n\nIf I had to choose one posterior, I would choose the one that had the prior of the match data from the previous year. I would choose this because it is based on real data, and had a very similar prior mean to posterior mean. Its prior mean (0.69697) was also extremely similar to the observed data from the French Open's match (0.66667).\n\n**The variance of each posterior should be different. Why do you think one posterior has a lower variance than the other two?**\n\nOne posterior has a lower variance than the other two: the announcer's informative posterior. This is because the prior had specific requirements that needed to be met, which meant the alpha and beta parameters of the prior were extremely large - 252 and 84, so there is a higher level of confidence. \n\n## Brief conclusion of what I found in this mini-project\n\nFrom the three posteriors, it appears that Nadal would win between 65% and 75% of his serves against Djokovic. The prior that had much higher alpha and beta parameters (announcer's) has much lower variance in the posterior than the non-informative, or the one based on last year's match data. The stronger the prior beliefs are, the less the posterior will be updated by real data.\n\nI think one takeaway is also that it is more reliable to trust real data, or to use a non-informative prior, rather than being overly confident in the precision of somebody's subjective guess.\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}